// Generated by CoffeeScript 1.6.2
(function() {
  var Doors, House, Roof, Windows, myFriendHouse, myNewHouse;

  Windows = (function() {
    function Windows() {
      this.windows = "windows,";
    }

    return Windows;

  })();

  Doors = (function() {
    function Doors() {
      this.doors = "doors,";
    }

    return Doors;

  })();

  Roof = (function() {
    function Roof() {
      this.roof = "roof";
    }

    return Roof;

  })();

  House = (function() {
    function House(prop) {
      this.buildHouse = function(prop) {
        var doors, roof, windows;

        if (prop === false || !prop) {
          console.log("You can't have same house as mine");
          return false;
        } else if (prop === true) {
          windows = new Windows();
          doors = new Doors();
          roof = new Roof();
          return console.log("My house has a " + windows.windows + doors.doors + "and a " + roof.roof);
        }
      };
      this.buildHouse(prop);
    }

    return House;

  })();

  myNewHouse = new House(true);

  myFriendHouse = new House();

}).call(this);
