// Generated by CoffeeScript 1.6.2
(function() {
  var Doors, House, HouseFactory, Roof, Windows, house, secondHouse;

  Windows = (function() {
    function Windows() {
      this.windows = "windows,";
    }

    return Windows;

  })();

  Doors = (function() {
    function Doors() {
      this.doors = "doors,";
    }

    return Doors;

  })();

  Roof = (function() {
    function Roof() {
      this.roof = "roof";
    }

    return Roof;

  })();

  House = (function() {
    function House() {
      this.buildHouse = function() {
        var doors, roof, windows;

        windows = new Windows();
        doors = new Doors();
        roof = new Roof();
        return console.log("My house has a " + windows.windows + doors.doors + "and a " + roof.roof);
      };
      this.buildHouse();
    }

    return House;

  })();

  HouseFactory = (function() {
    function HouseFactory() {
      new House();
    }

    return HouseFactory;

  })();

  house = new HouseFactory();

  secondHouse = new HouseFactory();

  terminal.log(house);

  terminal.log(secondHouse);

}).call(this);
