// Generated by CoffeeScript 1.6.2
(function() {
  this.singleton = (function() {
    var private_property;

    private_property = "some privacy";
    return {
      public_access: private_property,
      simple_public_method: function() {
        return "Hello Sigleton Module Pattern";
      }
    };
  })();

  this.singleton.public_access;

}).call(this);
