// Generated by CoffeeScript 1.6.2
(function() {
  var main_obj, sub_obj;

  main_obj = {
    func: function(name) {
      return console.log(name);
    }
  };

  sub_obj = {};

  main_obj.func.call(sub_obj, "command pattern");

}).call(this);
