// Generated by CoffeeScript 1.6.2
(function() {
  this.Main = (function() {
    function Main() {
      this.price = function(price) {
        if (price == null) {
          price = 100;
        }
        return price + " €";
      };
    }

    return Main;

  })();

  this.main = new Main;

  this.addTax = function(main) {
    var m, v;

    m = main.price();
    v = parseInt(m);
    return main.price = function() {
      return v * 0.73 + " €";
    };
  };

  this.addCosts = function(main) {
    var m, v;

    m = main.price();
    v = parseInt(m);
    return main.price = function() {
      return (v + 16) + " €";
    };
  };

}).call(this);
