// Generated by CoffeeScript 1.6.2
(function() {
  var arr, i, len;

  arr = ["blue", "green", "red", "yellow", "black"];

  i = 0;

  len = arr.length;

  this.obj = {};

  obj.current = function() {
    return arr[i];
  };

  obj.next = function() {
    if (arr[i] === "black") {
      this.reset();
      return arr[i];
    }
    return arr[++i];
  };

  obj.reset = function() {
    return i = 0;
  };

}).call(this);
