// Generated by CoffeeScript 1.6.2
(function() {
  var main_obj, sub_obj;

  main_obj = {
    exec: function(name) {
      return name;
    }
  };

  sub_obj = {};

  main_obj.exec.call(sub_obj, "command pattern");

}).call(this);
