// Generated by CoffeeScript 1.6.2
(function() {
  var Memento;

  Memento = (function() {
    function Memento() {
      this._prev = {};
      this.setProperty = function(key, val) {
        this[key] = val;
        return this._prev[key] = val;
      };
      this.getProperty = function(key) {
        return this[key];
      };
    }

    return Memento;

  })();

  this.memento = new Memento();

}).call(this);
