// Generated by CoffeeScript 1.6.2
(function() {
  this.pub = {
    topics: [],
    publish: function(title) {
      var key, val, _i, _len, _ref;

      _ref = this.topics;
      for (val = _i = 0, _len = _ref.length; _i < _len; val = ++_i) {
        key = _ref[val];
        if (this.topics[val] === title) {
          console.log("Topic already added");
          return;
        }
      }
      if (title === "" || !title) {
        console.log("You must enter a topic name");
        return;
      }
      return this.topics.push(title);
    }
  };

  this.sub = {
    messages: [],
    subscribe: function(title) {
      var key, val, _i, _len, _ref;

      if (pub.topics.length === 0) {
        console.log("No entries");
        return;
      }
      _ref = pub.topics;
      for (val = _i = 0, _len = _ref.length; _i < _len; val = ++_i) {
        key = _ref[val];
        if (pub.topics[val] === title) {
          if (pub.topics[val] === this.messages[val]) {
            console.log("You are already subscribed");
            return;
          }
          this.messages[val] = pub.topics[val];
          console.log("You are subscribed to " + title.toUpperCase() + " topic");
          if (pub.topics[val] !== title) {
            console.log("No such a topic");
          }
        }
      }
    }
  };

}).call(this);
