// Generated by CoffeeScript 1.6.2
(function() {
  var i, isNum, isString;

  this.client = function(user_input) {
    if (typeof user_input === "string") {
      return isString(user_input);
    } else if (typeof user_input === "number") {
      return isNum(user_input);
    } else if (typeof user_input === "boolean") {
      return isBool(user_input);
    }
  };

  this.store = [];

  i = 0;

  isString = function(user_input) {
    if (user_input === "miro") {
      store[i++] = user_input;
      return console.log("Your input " + user_input + " has been stored");
    } else {
      return console.log("Wrong name");
    }
  };

  isNum = function(user_input) {
    if (user_input > 10) {
      store[i++] = user_input;
      return console.log("Your input " + user_input + " has been stored");
    } else {
      return console.log("Wrong number");
    }
  };

}).call(this);
