// Generated by CoffeeScript 1.6.2
(function() {
  (function() {
    if (window.console && typeof window.console === "object") {
      return this.terminal = {
        name: "terminal name",
        error_message: "some kind of error",
        warning: "you are warned",
        log: function(message) {
          return console.log(message);
        },
        warn: function(message) {
          return console.warn(message);
        },
        error: function(message) {
          return console.error(message);
        }
      };
    } else {
      return alert("Console object is not supported in your browser");
    }
  })();

}).call(this);
