// Generated by CoffeeScript 1.6.2
(function() {
  var Driver, Jazz, driver, jazzPlayer;

  Jazz = (function() {
    function Jazz() {
      this.getPlayer = function(index) {
        var players;

        players = ["Charlie Parker", "Miles Davis", "John Coltrane"];
        return players[index];
      };
    }

    return Jazz;

  })();

  jazzPlayer = new Jazz();

  Driver = (function() {
    function Driver() {
      this.drive = function() {
        return console.log("I am a driver, and I like jazz");
      };
      this.listenJazz = function(index) {
        return console.log("Driver listening to " + jazzPlayer.getPlayer(index));
      };
    }

    return Driver;

  })();

  driver = new Driver();

}).call(this);
