// Generated by CoffeeScript 1.6.2
(function() {
  this.Car = (function() {
    function Car() {
      this.price = function(price) {
        if (price == null) {
          price = 100;
        }
        return price + " €";
      };
    }

    return Car;

  })();

  this.car = new Car;

  this.Decorator = (function() {
    function Decorator(obj) {
      this.addTax = function(obj) {
        var m, v;

        m = obj.price();
        v = parseInt(m);
        obj.price = function() {
          return v * 0.73 + " €";
        };
        return obj.price();
      };
      this.addCosts = function(obj) {
        var m, v;

        m = obj.price();
        v = parseInt(m);
        obj.price = function() {
          return (v + 16) + " €";
        };
        return obj.price();
      };
    }

    return Decorator;

  })();

  this.decorator = new Decorator();

}).call(this);
